# Generated by Django 6.0.5 on 2026-05-24 22:04

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArancelBusquedaCompleta',
            fields=[
                ('codigo_nacional', models.CharField(help_text='10 u 11 dígitos', max_length=11, primary_key=True, serialize=False)),
                ('codigo_nandina', models.CharField(db_index=True, max_length=8)),
                ('codigo_subpartida', models.CharField(db_index=True, max_length=6)),
                ('codigo_partida', models.CharField(db_index=True, max_length=4)),
                ('codigo_capitulo', models.CharField(db_index=True, max_length=2)),
                ('id_seccion', models.CharField(db_index=True, max_length=10)),
                ('descripcion_mercancia', models.TextField(help_text='Glosa específica del arancel')),
                ('descripcion_capitulo', models.TextField(blank=True, null=True)),
                ('descripcion_seccion', models.TextField(blank=True, null=True)),
                ('ga_porcentaje', models.DecimalField(db_index=True, decimal_places=2, max_digits=5)),
                ('ice_porcentaje', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('iehd', models.CharField(blank=True, max_length=100, null=True)),
                ('unidad_medida', models.CharField(blank=True, max_length=20, null=True)),
                ('documento_adicional', models.TextField(blank=True, help_text='Ej: SENASAG, IBMETRO', null=True)),
                ('preferencia_arancelaria_ace', models.TextField(blank=True, help_text='Ej: ACE 36, CAN', null=True)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(blank=True, null=True)),
            ],
            options={
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='arancel_search_vector_idx')],
            },
        ),
    ]
