# Generated by Django 6.0.5 on 2026-05-28 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Capitulo',
            fields=[
                ('codigo', models.CharField(help_text="Código de 2 dígitos (ej: '01')", max_length=2, primary_key=True, serialize=False)),
                ('descripcion', models.TextField(help_text='Nombre oficial del capítulo')),
                ('notas_legales', models.TextField(blank=True, help_text='Notas legales del capítulo (críticas para clasificación)', null=True)),
                ('seccion', models.CharField(blank=True, help_text="Sección a la que pertenece (ej: 'I')", max_length=10, null=True)),
            ],
            options={
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='NomenclaturaArancelaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('PARTIDA', 'Partida'), ('AGRUPACION', 'Agrupación'), ('SUBPARTIDA_SA', 'Subpartida SA'), ('NANDINA', 'NANDINA'), ('SUBPARTIDA_NACIONAL', 'Subpartida Nacional')], max_length=25)),
                ('codigo_oficial', models.CharField(blank=True, db_index=True, help_text='Código oficial (null para agrupaciones)', max_length=20, null=True)),
                ('descripcion', models.TextField()),
                ('orden', models.IntegerField(default=0, help_text='Orden dentro del padre para respetar el arancel')),
                ('is_leaf', models.BooleanField(db_index=True, default=False, help_text='True si es Subpartida Nacional (nodo operativo)')),
                ('ga_porcentaje', models.DecimalField(blank=True, decimal_places=2, help_text='Gravamen Arancelario en %', max_digits=5, null=True)),
                ('ice_iehd', models.CharField(blank=True, help_text='ICE o IEHD aplicable', max_length=100, null=True)),
                ('unidad_medida', models.CharField(blank=True, help_text='Unidad de medida (kg, u, L, etc.)', max_length=20, null=True)),
                ('despacho_frontera', models.CharField(blank=True, help_text='Indicación de despacho en frontera', max_length=100, null=True)),
                ('notas_explicativas', models.TextField(blank=True, help_text='Notas explicativas OMA o resumen IA cacheado', null=True)),
                ('capitulo', models.ForeignKey(help_text='Capítulo al que pertenece', on_delete=django.db.models.deletion.CASCADE, related_name='nomenclaturas', to='api.capitulo')),
                ('parent', models.ForeignKey(blank=True, help_text='Nodo padre en el árbol', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hijos', to='api.nomenclaturaarancelaria')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notas_personales', models.TextField(blank=True, help_text='Notas privadas del despachante sobre esta partida', null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to=settings.AUTH_USER_MODEL)),
                ('nomenclatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos_de_usuarios', to='api.nomenclaturaarancelaria')),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoAdicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_doc', models.CharField(help_text="Tipo de documento (ej: 'C*')", max_length=20)),
                ('entidad_emisora', models.CharField(help_text="Entidad que emite (ej: 'MDPRyA (SENASAG)')", max_length=200)),
                ('disposicion_legal', models.CharField(blank=True, help_text='Norma legal de respaldo', max_length=200, null=True)),
                ('nomenclatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_adicionales', to='api.nomenclaturaarancelaria')),
            ],
            options={
                'ordering': ['nomenclatura', 'tipo_doc'],
            },
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('expira_en', models.DateTimeField()),
                ('usado', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='PreferenciaArancelaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_acuerdo', models.CharField(choices=[('CAN', 'Comunidad Andina'), ('ACE_36', 'ACE 36 - Mercosur'), ('ACE_47', 'ACE 47'), ('VEN', 'Venezuela'), ('ACE_22_CHI', 'ACE 22 Chile'), ('ACE_22_PROT', 'ACE 22 Protocolo'), ('ACE_66_MEX', 'ACE 66 México')], max_length=20)),
                ('porcentaje_desgravacion', models.DecimalField(decimal_places=2, help_text='% de desgravación (0-100)', max_digits=5)),
                ('nomenclatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferencias', to='api.nomenclaturaarancelaria')),
            ],
            options={
                'ordering': ['nomenclatura', 'tipo_acuerdo'],
            },
        ),
        migrations.CreateModel(
            name='HistorialConsulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('BUSQUEDA', 'Búsqueda por texto/código'), ('EXPLORACION', 'Exploración del árbol'), ('IA_CLASIFIC', 'Clasificación IA'), ('IA_RESUMEN', 'Resumen notas IA'), ('CALCULO', 'Cálculo de tributos')], max_length=20)),
                ('query', models.TextField(help_text='Término o pregunta realizada')),
                ('resultado_codigo', models.CharField(blank=True, help_text='Código arancelario resultante (si aplica)', max_length=20, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Datos adicionales según el tipo de consulta')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_consultas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['usuario', '-timestamp'], name='api_histori_usuario_2eea79_idx'), models.Index(fields=['tipo', '-timestamp'], name='api_histori_tipo_6631de_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='nomenclaturaarancelaria',
            index=models.Index(fields=['capitulo', 'orden'], name='api_nomencl_capitul_6c28af_idx'),
        ),
        migrations.AddIndex(
            model_name='nomenclaturaarancelaria',
            index=models.Index(fields=['is_leaf', 'codigo_oficial'], name='api_nomencl_is_leaf_e54d03_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='favorito',
            unique_together={('usuario', 'nomenclatura')},
        ),
        migrations.AlterUniqueTogether(
            name='preferenciaarancelaria',
            unique_together={('nomenclatura', 'tipo_acuerdo')},
        ),
    ]
