# Generated by Django 6.0.5 on 2026-05-25 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arancelbusquedacompleta',
            name='codigo_nacional',
            field=models.CharField(max_length=11, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='arancelbusquedacompleta',
            name='descripcion_mercancia',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='arancelbusquedacompleta',
            name='documento_adicional',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='arancelbusquedacompleta',
            name='preferencia_arancelaria_ace',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='NomenclaturaArancelaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('CAPITULO', 'Capítulo'), ('PARTIDA', 'Partida'), ('AGRUPACION', 'Agrupación'), ('SUBPARTIDA_SA', 'Subpartida SA'), ('SUBPARTIDA_NACIONAL', 'Subpartida Nacional')], max_length=25)),
                ('codigo_oficial', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('descripcion', models.TextField()),
                ('orden', models.IntegerField(default=0)),
                ('is_leaf', models.BooleanField(default=False)),
                ('ga_porcentaje', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ice_porcentaje', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('unidad_medida', models.CharField(blank=True, max_length=20, null=True)),
                ('doc_adicional', models.TextField(blank=True, null=True)),
                ('preferencias', models.TextField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hijos', to='api.nomenclaturaarancelaria')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
    ]
